ci(python): don't install gpu support for tensorflow and torch
Because the available disk space in GHA is limited, we were running into this issue when installing the libraries with cuda:

ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

Because GPUs are anyway not available, this solution is just better.